name: 'Test Unit'
description: 'Running unit tests'

runs:
  using: "composite"
  steps:
    - uses: Swatinem/rust-cache@v1

    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --no-fail-fast
      env:
        RUST_TEST_THREADS: '2'
        RUST_LOG: ERROR
        RUST_BACKTRACE: full
