[package]
name = "ovfs"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
libc = "0.2.139"
vhost = "0.11.0"
bitflags = "1.2"
env_logger = "0.11.3"
sharded-slab = "0.1.7"
virtio-queue = "0.11.0"
vmm-sys-util = "0.12.1"
virtio-bindings = "0.2.1"
vhost-user-backend = "0.14.0"
opendal = { version = "0.46.0", features = ["services-s3"] }
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
vm-memory = { version = "0.14.0", features = ["backend-mmap", "backend-atomic"] }
