version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for opendal
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for oay
  - package-ecosystem: "cargo"
    directory: "/oay"
    schedule:
      interval: "daily"

  # Maintain dependencies for oli
  - package-ecosystem: "cargo"
    directory: "/oli"
    schedule:
      interval: "daily"
