[package]
authors = ["Databend Authors <opensource@datafuselabs.com>"]
categories = ["filesystem"]
description = "Open Data Access Layer that connect the whole world together."
edition = "2021"
keywords = ["storage", "data", "s3"]
license = "Apache-2.0"
name = "opendal"
repository = "https://github.com/datafuselabs/opendal"
version = "0.2.1"

[workspace]
members = ["opendal_test"]

[lib]
bench = false

[[bench]]
harness = false
name = "ops"

[dependencies]
anyhow = "1"
async-trait = "0.1"
aws-config = "0.8"
aws-endpoint = "0.8"
aws-http = "0.8"
aws-sdk-s3 = "0.8"
aws-sig-auth = "0.8"
aws-sigv4 = "0.8"
aws-smithy-client = "0.38"
aws-smithy-http = "0.38"
aws-smithy-http-tower = "0.38"
aws-types = { version = "0.8", features = ["hardcoded-credentials"] }
blocking = "1"
bytes = "1"
futures = { version = "0.3", features = ["alloc"] }
http = "0.2"
hyper = { version = "0.14", features = ["stream"] }
log = "0.4"
metrics = "0.18"
once_cell = "1"
pin-project = "1"
reqwest = "0.11"
thiserror = "1"
tower = "0.4"

[dev-dependencies]
anyhow = "1.0"
criterion = { version = "0.3", features = [
  "async",
  "async_tokio",
  "html_reports",
] }
dotenv = "0.15"
env_logger = "0.9"
num-traits = "0.2"
opendal_test = { path = "./opendal_test" }
rand = "0.8"
sha2 = "0.10"
size = "0.1"
tokio = { version = "1.16", features = ["full"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
