[package]
name = "opendal"
version = "0.1.2"
edition = "2021"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
description = "Open Data Access Layer that connect the whole world together."
repository = "https://github.com/datafuselabs/opendal"
keywords = ["storage", "data", "s3"]
categories = ["filesystem"]

[workspace]
members = [
    "opendal_test",
]

[lib]
bench = false

[[bench]]
name = "ops"
harness = false

[dependencies]
async-trait = "0.1"
bytes = "1"
futures = { version = "0.3", features = ["alloc"] }
thiserror = "1"
aws-types = { version = "0.6", features = ["hardcoded-credentials"] }
aws-sdk-s3 = "0.6"
aws-endpoint = "0.6"
http = "0.2.6"
aws-smithy-http = "0.36"
hyper = { version = "0.14", features = ["stream"] }
pin-project = "1"
aws-config = "0.6"
blocking = "1"
anyhow = "1"
reqwest = "0.11"
once_cell = "1"
bitflags = "1"

[dev-dependencies]
uuid = { version = "0.8", features = ["serde", "v4"] }
anyhow = "1.0"
rand = "0.8"
sha2 = "0.10"
criterion = { version = "0.3", features = ["async", "async_tokio", "html_reports"] }
tokio = { version = "1.16", features = ["full"] }
dotenv = "0.15"
opendal_test = { path = "./opendal_test" }
