[package]
name = "opendal"
version = "0.0.5"
edition = "2021"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
description = "Open Data Access Layer that connect the whole world together."
repository = "https://github.com/datafuselabs/opendal"
keywords = ["storage", "data", "s3"]
categories = ["filesystem"]

[lib]
bench = false

[[bench]]
name = "ops"
harness = false

[dependencies]
async-trait = "0.1.52"
bytes = "1"
futures = { version = "0.3.21", features = ["alloc"] }
thiserror = "1"
aws-types = { version = "0.6.0", features = ["hardcoded-credentials"] }
aws-sdk-s3 = "0.6.0"
aws-endpoint = "0.6.0"
http = "0.2.6"
aws-smithy-http = "0.36.0"
hyper = { version = "0.14.16", features = ["stream"] }
pin-project = "1.0.10"
aws-config = "0.6.0"
blocking = "1.1.0"
anyhow = "1"

[dev-dependencies]
uuid = { version = "0.8.2", features = ["serde", "v4"] }
anyhow = "1.0"
rand = "0.8.5"
sha2 = "0.10.1"
criterion = { version = "0.3", features = ["async", "async_tokio", "html_reports"] }
tokio = { version = "1.16.1", features = ["full"] }
dotenv = "0.15.0"