[package]
authors = ["Databend Authors <opensource@datafuselabs.com>"]
categories = ["filesystem"]
description = "Open Data Access Layer that connect the whole world together."
edition = "2021"
keywords = ["storage", "data", "s3", "fs"]
license = "Apache-2.0"
name = "opendal"
repository = "https://github.com/datafuselabs/opendal"
version = "0.3.0"

[workspace]
members = ["opendal_test"]

[lib]
bench = false

[[bench]]
harness = false
name = "ops"

[[bench]]
harness = false
name = "io"

[dependencies]
anyhow = "1"
async-compat = "0.2"
async-trait = "0.1"
base64 = "0.13.0"
bytes = "1.1.0"
futures = { version = "0.3", features = ["alloc"] }
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
hyper-tls = "0.5.0"
log = "0.4"
md5 = "0.7.0"
metrics = "0.18"
minitrace = "0.4.0"
once_cell = "1"
pin-project = "1"
quick-xml = { version = "0.22.0", features = ["serialize"] }
reqsign = "0.0.3"
reqwest = { version = "0.11", features = ["stream"] }
roxmltree = "0.14"
serde = { version = "1.0.136", features = ["derive"] }
thiserror = "1"
time = "0.3.7"
tokio = { version = "1.17", features = ["full"] }

[dev-dependencies]
anyhow = "1.0"
criterion = { version = "0.3", features = [
  "async",
  "async_tokio",
  "html_reports",
] }
dotenv = "0.15"
env_logger = "0.9"
num-traits = "0.2"
opendal_test = { path = "./opendal_test" }
paste = "1.0.7"
rand = "0.8"
serde_json = "1.0.79"
sha2 = "0.10"
size = "0.1"
uuid = { version = "0.8", features = ["serde", "v4"] }
