[package]
authors = ["Databend Authors <opensource@datafuselabs.com>"]
categories = ["filesystem"]
description = "Open Data Access Layer that empowers everyone to access different storage services painless and efficiently."
edition = "2021"
exclude = ["docs/"]
homepage = "https://opendal.databend.rs/"
keywords = ["storage", "data", "s3", "fs", "azblob"]
license = "Apache-2.0"
name = "opendal"
repository = "https://github.com/datafuselabs/opendal"
version = "0.11.3"

[package.metadata.docs.rs]
all-features = true

[features]
default = ["hyper-tls"]

# Enable compress support so that users can decompress while reading.
compress = ["async-compression"]
# Enable retry layer support.
retry = ["backon"]
# Enable rustls support.
rustls = ["hyper-rustls"]
# Enable serde support.
serde = ["time/serde"]
# Enable services hdfs support
services-hdfs = ["hdrs"]
# Enable services http support
services-http = ["radix_trie"]

[lib]
bench = false

[[bench]]
harness = false
name = "ops"

[[bench]]
harness = false
name = "io"

[[example]]
name = "hdfs"
required-features = ["services-hdfs"]

[dependencies]
anyhow = "1.0"
async-compat = "0.2"
# Temp workaround, should come back to tagged version after https://github.com/Nemo157/async-compression/issues/150 resolved.
async-compression = { package = "async-compression-issue-150-workaround", version = "0.3.15-issue-150", features = [
  "futures-io",
  "all-algorithms",
], optional = true }
async-trait = "0.1"
backon = { version = "0.0.2", optional = true }
base64 = "0.13"
bytes = "1.1"
dotenv = { version = "0.15", optional = true }
flagset = "0.4"
futures = { version = "0.3", features = ["alloc"] }
hdrs = { version = "0.1", optional = true, features = ["futures-io"] }
http = "0.2"
hyper = { version = "0.14", features = [
  "http1",
  "http2",
  "client",
  "runtime",
  "stream",
] }
hyper-rustls = { version = "0.23", optional = true, features = [
  "rustls-native-certs",
] }
hyper-tls = { version = "0.5", optional = true }
log = "0.4"
md5 = "0.7"
metrics = "0.20"
minitrace = "0.4"
once_cell = "1.10"
parking_lot = "0.12"
percent-encoding = "2.1"
pin-project = "1.0"
quick-xml = { version = "0.23", features = ["serialize"] }
radix_trie = { version = "0.2", optional = true }
reqsign = "0.3"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
time = "0.3"
tokio = { version = "1.20", features = ["fs"] }

[dev-dependencies]
cfg-if = "1.0"
criterion = { version = "0.3", features = [
  "async",
  "async_tokio",
  "html_reports",
] }
dotenv = "0.15"
env_logger = "0.9"
hyper-tls = "0.5"
itertools = "0.10"
num-traits = "0.2"
paste = "1.0"
rand = "0.8"
serde_json = "1.0"
sha2 = "0.10"
size = "0.4"
tokio = { version = "1.20", features = ["fs", "macros", "rt-multi-thread"] }
uuid = { version = "1.0", features = ["serde", "v4"] }
wiremock = "0.5"
