[package]
authors = ["Databend Authors <opensource@datafuselabs.com>"]
categories = ["filesystem"]
description = "Open Data Access Layer that connect the whole world together."
edition = "2021"
keywords = ["storage", "data", "s3"]
license = "Apache-2.0"
name = "opendal"
repository = "https://github.com/datafuselabs/opendal"
version = "0.1.3"

[workspace]
members = ["opendal_test"]

[lib]
bench = false

[[bench]]
harness = false
name = "ops"

[dependencies]
anyhow = "1"
async-trait = "0.1"
aws-config = "0.8"
aws-endpoint = "0.8"
aws-sdk-s3 = "0.8"
aws-smithy-http = "0.38"
aws-types = { version = "0.8", features = ["hardcoded-credentials"] }
bitflags = "1"
blocking = "1"
bytes = "1"
futures = { version = "0.3", features = ["alloc"] }
http = "0.2"
hyper = { version = "0.14", features = ["stream"] }
once_cell = "1"
pin-project = "1"
reqwest = "0.11"
thiserror = "1"

[dev-dependencies]
anyhow = "1.0"
criterion = { version = "0.3", features = [
  "async",
  "async_tokio",
  "html_reports",
] }
dotenv = "0.15"
opendal_test = { path = "./opendal_test" }
rand = "0.8"
sha2 = "0.10"
tokio = { version = "1.16", features = ["full"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
