# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

headerPath = "Apache-2.0-ASF.txt"

excludes = [
  "**/*.toml",
  "!**/Cargo.toml",
  "!**/licenserc.toml",
  "!**/pyproject.toml",

  # Generated files
  "**/Cargo.lock",
  "**/yarn.lock",
  "**/fixtures/**",
  "tests/data/**",
  "bindings/nodejs/.npmignore",
  "bindings/nodejs/.prettierignore",
  "bindings/nodejs/generated*.*",
  "**/*.node",
  "bindings/python/test_requirements.txt",
  "bindings/python/opendal.pyi",
  "**/__pycache__",
  "**/.pytest_cache",
  "**/venv/**",
  "website/build/**",
  "website/static/.nojekyll",
  "website/.docusaurus",

  # Files that doesn't need license.
  ".env.example",
  ".env",

  # ascii is licensed under MIT from memcache-async
  "core/src/services/memcached/MIT-ascii.txt",
  "core/src/services/memcached/ascii.rs",
]

[properties]
inceptionYear = 2023
