[package]
name = "add-layers"

edition = "2021"
version = "0.1.0"

[dependencies]
futures = "0.3"
opendal = "0.45"
env_logger = "0.11"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
