[package]
edition = "2021"
name = "opendal-nodejs"
version = "0.0.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2"
napi-derive = "2"
opendal = { version = "0.27", path = "../../" }

[build-dependencies]
napi-build = "2"
