# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

[package]
edition = "2021"
name = "opendal-nodejs"
version = "0.30.2"

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = "0.3.26"
napi = { version = "2.11.3", default-features = false, features = [
  "napi6",
  "async",
] }
napi-derive = "2.11.1"
opendal = { version = "0.30", path = "../../" }
time = { version = "0.3.17", features = ["formatting"] }

[build-dependencies]
napi-build = "2"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
rustflags = ["-C", "target-feature=-crt-static"]
