[package]
edition = "2021"
name = "opendal-python"
version = "0.0.1"

[lib]
crate-type = ["cdylib"]
name = "opendal"

[dependencies]
opendal = { version = "0.25", path = "../../" }
pyo3 = { version = "0.18", features = ["extension-module"] }
