[package]
name = "opendal-fuzz"
version = "0.0.0"
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
anyhow = "1.0.71"
arbitrary = { version = "1.3.0", features = ["derive"] }
libfuzzer-sys = "0.4"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.4.0", features = ["v4"] }


[dependencies.opendal]
path = ".."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[profile.release]
debug = 1

[[bin]]
name = "fuzz_reader_fs"
path = "fuzz_targets/fuzz_reader_fs.rs"
test = false
doc = false
