# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Test Integration CloudFilter
description: 'Test Integration CloudFilter'

runs:
  using: composite
  steps:
    - name: Setup
      shell: bash
      run: |
        mkdir -p ./dynamic_test_integration_cloudfilter &&
        cat <<EOF >./dynamic_test_integration_cloudfilter/action.yml
        runs:
          using: composite
          steps:
          # FIXME: cloudfilter is readonly currently
          # so behavior tests uses fs scheme with fixtures/data as root to test
          # - name: Setup Test
          #   uses: ./.github/services/${{ inputs.service }}/${{ inputs.setup }}
          - name: Run Test CloudFilter
            shell: pwsh
            working-directory: integrations/cloudfilter
            run: cargo test --test behavior
            env:
              OPENDAL_TEST: fs
              OPENDAL_FS_ROOT: ../../fixtures/data
              OPENDAL_DISABLE_RANDOM_ROOT: 'true'
        EOF
    - name: Run
      uses: ./dynamic_test_integration_cloudfilter
