# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: etcd-cluster-tls
description: 'Behavior test for etcd-cluster-tls'

runs:
    using: "composite"
    steps:
    - name: Copy Etcd Certificate Files
      shell: bash
      working-directory: fixtures
      run: |
        mkdir -p /tmp/etcd
        cp -r `pwd`/etcd/* /tmp/etcd
    - name: Configure Etcd Service With TLS
      shell: bash
      run: |
        # Create docker network
        docker network create -d bridge --subnet=176.16.12.0/24 --gateway=176.16.12.1 etcd-tls-net

        # Launch etcd
        for no in `seq 0 2`; do \
            num=$((no+1))
            ip=$((no+2))

            docker run -d \
            -p 2379${no}:2379 \
            -p 2380${no}:2380 \
            --network etcd-tls-net \
            --name etcd-tls-${num} \
            --ip 176.16.12.${ip} \
            -v /tmp/etcd/ca.pem:/opt/bitnami/etcd/conf/ca.pem \
            -v /tmp/etcd/server.pem:/opt/bitnami/etcd/conf/server.pem \
            -v /tmp/etcd/server-key.pem:/opt/bitnami/etcd/conf/server-key.pem \
            -v /tmp/etcd/client-key.pem:/opt/bitnami/etcd/client-key.pem \
            -v /tmp/etcd/client.pem:/opt/bitnami/etcd/client.pem \
            -v /tmp/etcd/etcd${num}/etcd.pem:/opt/bitnami/etcd/conf/peer.pem \
            -v /tmp/etcd/etcd${num}/etcd-key.pem:/opt/bitnami/etcd/conf/peer-key.pem \
            -e ETCD_ROOT_PASSWORD=opendal \
            -e ETCD_CLIENT_CERT_AUTH=true \
            -e ETCD_PEER_CLIENT_CERT_AUTH=true \
            -e ETCD_NAME=etcd${num} \
            -e ETCD_INITIAL_ADVERTISE_PEER_URLS=https://176.16.12.${ip}:2380 \
            -e ETCD_LISTEN_PEER_URLS=https://0.0.0.0:2380 \
            -e ETCD_LISTEN_CLIENT_URLS=https://0.0.0.0:2379 \
            -e ETCD_ADVERTISE_CLIENT_URLS=https://176.16.12.${ip}:2379 \
            -e ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster \
            -e ETCD_INITIAL_CLUSTER=etcd1=https://176.16.12.2:2380,etcd2=https://176.16.12.3:2380,etcd3=https://176.16.12.4:2380 \
            -e ETCD_INITIAL_CLUSTER_STATE=new \
            -e ETCD_MAX_REQUEST_BYTES=10485760 \
            -e ETCD_TRUSTED_CA_FILE=/opt/bitnami/etcd/conf/ca.pem \
            -e ETCD_KEY_FILE=/opt/bitnami/etcd/conf/server-key.pem \
            -e ETCD_CERT_FILE=/opt/bitnami/etcd/conf/server.pem \
            -e ETCD_PEER_TRUSTED_CA_FILE=/opt/bitnami/etcd/conf/ca.pem \
            -e ETCD_PEER_KEY_FILE=/opt/bitnami/etcd/conf/peer-key.pem \
            -e ETCD_PEER_CERT_FILE=/opt/bitnami/etcd/conf/peer.pem \
            bitnami/etcd:latest
        done

    - name: Setup
      shell: bash
      run: |
          cat << EOF >> $GITHUB_ENV
          OPENDAL_ETCD_ENDPOINTS=https://127.0.0.1:23790,https://127.0.0.1:23791,https://127.0.0.1:23792
          OPENDAL_ETCD_ROOT=/tmp/opendal
          OPENDAL_ETCD_USERNAME=root
          OPENDAL_ETCD_PASSWORD=opendal
          OPENDAL_ETCD_CA_PATH=/tmp/etcd/ca.pem
          OPENDAL_ETCD_CERT_PATH=/tmp/etcd/client.pem
          OPENDAL_ETCD_KEY_PATH=/tmp/etcd/client-key.pem
