[package]
name = "edge_test_file_write_on_full_disk"
edition = "2021"
version = "0.0.0"
publish = false

[dependencies]
futures = "0.3"
opendal = { workspace = true }
tokio = { version = "1", features = ["full"] }
rand = "0.8"
