name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/check
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ${{ matrix.os }}
    needs: check
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build

  test_unit:
    runs-on: ${{ matrix.os }}
    needs: check
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test_unit
