name: Docs

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout java env
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps --all-features
        env:
          LD_LIBRARY_PATH: ${{ env.JAVA_HOME }}/lib/server:${{ env.LD_LIBRARY_PATH }}

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - run: |
          mdbook build
          cp -r ./target/doc/* ./target/book

      - name: Deploy to vercel
        if: github.ref_name == 'main'
        env:
          VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
          VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}
        run: |
          npm i -g vercel
          vercel --token=${{ secrets.VERCEL_TOKEN }} --prod --scope databend ./target/book

      - name: Deploy to vercel (preview)
        if: github.ref_name != 'main'
        env:
          VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
          VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}
        run: |
          npm i -g vercel
          vercel --token=${{ secrets.VERCEL_TOKEN }} --scope databend ./target/book
