name: Service Test IPFS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  ipfs-daemon:
    runs-on: ubuntu-latest
    services:
      ipfs:
        image: ipfs/go-ipfs:v0.16.0
    steps:
      - uses: actions/checkout@v3
      - name: IPFS Add testdata
        run: |
          docker ps
          docker run $(docker ps -q) ipfs add -r ./tests/data --to-files /opendal-testdata
          docker run $(docker ps -q) ipfs files ls /opendal-testdata -l
      - uses: Swatinem/rust-cache@v2
      - name: Test
        shell: bash
        run: cargo test ipfs --features services-ipfs -- --show-output
        env:
          RUST_BACKTRACE: full
          RUST_LOG: debug
          OPENDAL_IPFS_TEST: on
          OPENDAL_IPFS_ROOT: /ipfs/QmPpCt1aYGb9JWJRmXRUnmJtVgeFFTJGzWFYEEX7bo9zGJ/
          OPENDAL_IPFS_ENDPOINT: "http://127.0.0.1:8080"
#  # ipfs.io can't pass our test by now, we should address them in the future.
#  ipfs-io:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Test
#        shell: bash
#        run: cargo test ipfs --features compress,services-ipfs -- --show-output
#        env:
#          RUST_BACKTRACE: full
#          RUST_LOG: debug
#          OPENDAL_IPFS_TEST: on
#          OPENDAL_IPFS_ROOT: /ipfs/QmPpCt1aYGb9JWJRmXRUnmJtVgeFFTJGzWFYEEX7bo9zGJ/
#          OPENDAL_IPFS_ENDPOINT: "https://ipfs.io"
