# Copyright 2022 Datafuse Labs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Service Test WebDAV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"
      - "!src/docs/**"
      - "!src/services/**"
      - "src/services/webdav/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  nginx:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install nginx full for dav_ext modules
        run: sudo apt install nginx-full

      - name: Start nginx
        shell: bash
        run: |
          mkdir -p /tmp/static
          nginx -c `pwd`/src/services/webdav/fixtures/nginx.conf

      - name: Test
        shell: bash
        run: cargo test webdav -- --show-output
        env:
          RUST_BACKTRACE: full
          RUST_LOG: debug
          OPENDAL_WEBDAV_TEST: on
          OPENDAL_WEBDAV_ENDPOINT: http://127.0.0.1:8080

  nginx_with_password:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install nginx full for dav_ext modules
        run: sudo apt install nginx-full

      - name: Start nginx
        shell: bash
        run: |
          mkdir -p /tmp/static
          cp `pwd`/src/services/webdav/fixtures/htpasswd /tmp/htpasswd
          nginx -c `pwd`/src/services/webdav/fixtures/nginx-with-basic-auth.conf

      - name: Test empty password
        shell: bash
        run: cargo test webdav -- --show-output
        env:
          RUST_BACKTRACE: full
          RUST_LOG: debug
          OPENDAL_WEBDAV_TEST: on
          OPENDAL_WEBDAV_ENDPOINT: http://127.0.0.1:8080
          OPENDAL_WEBDAV_USERNAME: foo

      - name: Test with password
        shell: bash
        run: cargo test webdav -- --show-output
        env:
          RUST_BACKTRACE: full
          RUST_LOG: debug
          OPENDAL_WEBDAV_TEST: on
          OPENDAL_WEBDAV_ENDPOINT: http://127.0.0.1:8080
          OPENDAL_WEBDAV_USERNAME: bar
          OPENDAL_WEBDAV_PASSWORD: bar
