name: Service Test Memory

on: [ push, pull_request ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  memory:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        shell: bash
        run: cargo test memory --features compress,retry,testing -- --nocapture
        env:
          RUST_BACKTRACE: full
          RUST_LOG: debug
          OPENDAL_MEMORY_TEST: on
