name: Service Test Moka

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  moka:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Xuanwo/sccache-action@be7e4cdfaeeadacaab1a25bc571e739f39c907a1
        with:
          version: "v0.4.0-pre.5"
      - name: Start sccache
        run: ${SCCACHE_PATH} --start-server
        env:
          SCCACHE_GHA_VERSION: opendal
      - name: Test
        shell: bash
        run: cargo test moka --features compress,services-moka -- --nocapture
        env:
          RUSTC_WRAPPER: ${{ env.SCCACHE_PATH }}
          RUST_BACKTRACE: full
          RUST_LOG: debug
          OPENDAL_MOKA_TEST: on
