name: Service Test Moka

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  moka:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        shell: bash
        run: cargo test moka --features compress,layers-retry,services-moka -- --nocapture
        env:
          RUST_BACKTRACE: full
          RUST_LOG: debug
          OPENDAL_MOKA_TEST: on
