# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Service Test Mysql

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "core/src/**"
      - "core/tests/**"
      - "!core/src/docs/**"
      - "!core/src/services/**"
      - "core/src/services/mysql/**"
      - ".github/workflows/service_test_mysql.yml"
      - "fixtures/mysql/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  mysql:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Mysql Server
        shell: bash
        working-directory: fixtures/mysql
        run: docker-compose -f docker-compose.yml up -d

      - name: Setup Rust toolchain
        uses: ./.github/actions/setup
        with:
          need-nextest: true

      - name: Test
        shell: bash
        working-directory: core
        run: cargo nextest run mysql --features services-mysql
        env:
          OPENDAL_MYSQL_TEST: on
          OPENDAL_MYSQL_CONNECTION_STRING: mysql://root:password@localhost:3306/testdb
          OPENDAL_MYSQL_TABLE: data
          OPENDAL_MYSQL_KEY_FIELD: key
          OPENDAL_MYSQL_VALUE_FIELD: data
