name: Service Test IPFS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  ipfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up IPFS ${{ matrix.ipfs }}
        uses: ibnesayeed/setup-ipfs@e183d0d2538b866dc30d8850883bd4cd4f8ab431
        id: ipfs_setup
        with:
          ipfs_version: "v0.14.0"
          run_daemon: true
      - name: Test
        shell: bash
        run: cargo test ipfs --features compress,layers-retry -- --nocapture
        env:
          RUST_BACKTRACE: full
          RUST_LOG: debug
          OPENDAL_IPFS_TEST: on
          OPENDAL_IPFS_ROOT: /opendal/
          OPENDAL_IPFS_ENDPOINT: "http://127.0.0.1:5001"
