name: Service Test RocksDB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  rocksdb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Xuanwo/sccache-action@be7e4cdfaeeadacaab1a25bc571e739f39c907a1
        with:
          version: "v0.4.0-pre.5"
      - name: Start sccache
        run: ${SCCACHE_PATH} --start-server
        env:
          SCCACHE_GHA_VERSION: opendal
      - name: Test
        shell: bash
        run: cargo test rocksdb --features compress,services-rocksdb -- --nocapture --test-threads=1
        env:
          RUSTC_WRAPPER: ${{ env.SCCACHE_PATH }}
          RUST_BACKTRACE: full
          RUST_LOG: debug
          OPENDAL_ROCKSDB_TEST: on
          OPENDAL_ROCKSDB_ROOT: /
          OPENDAL_ROCKSDB_DATADIR: /tmp/opendal/rocksdb/
