name: Service Test IPMFS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  ipmfs:
    runs-on: ubuntu-latest
    services:
      ipfs:
        image: ipfs/go-ipfs:v0.14.0
        ports:
          - 5001:5001
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Test
        shell: bash
        run: cargo test ipmfs --features compress -- --show-output
        env:
          RUST_BACKTRACE: full
          RUST_LOG: debug
          OPENDAL_IPFS_TEST: on
          OPENDAL_IPFS_ROOT: /opendal/
          OPENDAL_IPFS_ENDPOINT: "http://127.0.0.1:5001"
