name: Service Test HTTP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  nginx:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start nginx
        shell: bash
        run: |
          mkdir /tmp/static
          cp -r testdata/* /tmp/static
          nginx -c `pwd`/services/http/fixtures/nginx.conf

      - name: Test
        shell: bash
        run: cargo test http --features compress,layers-retry,services-http -- --nocapture
        env:
          RUST_BACKTRACE: full
          RUST_LOG: debug
          OPENDAL_HTTP_TEST: on
          OPENDAL_HTTP_ENDPOINT: http://127.0.0.1:80
