# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Service Test Azblob

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "core/src/**"
      - "core/tests/**"
      - "!core/src/docs/**"
      - "!core/src/services/**"
      - "core/src/services/azblob/**"
      - ".github/workflows/service_test_azblob.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  azurite_azblob:
    runs-on: ubuntu-latest

    # Setup azurite server
    services:
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000

    steps:
      - uses: actions/checkout@v4
      - name: Setup test bucket
        run: |
          az storage container create \
              --name test \
              --connection-string "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;"

      - name: Setup Rust toolchain
        uses: ./.github/actions/setup
        with:
          need-nextest: true

      - name: Test
        shell: bash
        working-directory: core
        run: cargo nextest run azblob
        env:
          RUST_BACKTRACE: full
          RUST_LOG: debug
          OPENDAL_AZBLOB_TEST: on
          OPENDAL_AZBLOB_CONTAINER: test
          OPENDAL_AZBLOB_ENDPOINT: "http://127.0.0.1:10000/devstoreaccount1"
          OPENDAL_AZBLOB_ACCOUNT_NAME: devstoreaccount1
          OPENDAL_AZBLOB_ACCOUNT_KEY: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==

  azure_azblob:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.repository == 'apache/incubator-opendal') || !github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: ./.github/actions/setup
        with:
          need-nextest: true

      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          OPENDAL_AZBLOB_TEST: op://services/azblob/test
          OPENDAL_AZBLOB_CONTAINER: op://services/azblob/container
          OPENDAL_AZBLOB_ENDPOINT: op://services/azblob/endpoint
          OPENDAL_AZBLOB_ACCOUNT_NAME: op://services/azblob/account_name
          OPENDAL_AZBLOB_ACCOUNT_KEY: op://services/azblob/account_key

      - name: Test
        shell: bash
        working-directory: core
        run: cargo nextest run azblob
