name: Service Test Ghac

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  ghac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Xuanwo/sccache-action@c94e27bef21ab3fb4a5152c8a878c53262b4abb0
        with:
          version: "v0.4.0-pre.6"
      - name: Start sccache
        run: ${SCCACHE_PATH} --start-server
        env:
          SCCACHE_GHA_ENABLED: on

      - name: Configure Cache Env
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Test
        shell: bash
        run: cargo test ghac --features compress -- --nocapture
        # Allow ghac test fail for rate limit
        continue-on-error: true
        env:
          RUSTC_WRAPPER: ${{ env.SCCACHE_PATH }}
          RUST_BACKTRACE: full
          RUST_LOG: debug
          OPENDAL_GHAC_TEST: ${{ secrets.OPENDAL_GHAC_TEST }}
          OPENDAL_GHAC_ENABLE_CREATE_SIMULATION: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
