name: Service Test Memcached

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  memcached:
    runs-on: ubuntu-latest

    # Setup memcached server
    services:
      memcached:
        image: bitnami/memcached
        env:
          # memcache's max item size is 1MiB, But opendal's behavior tests
          # will produce larger file.
          #
          # Specify the setting here to make our test happy.
          MEMCACHED_MAX_ITEM_SIZE: 16777216
        ports:
          - 11211:11211

    steps:
      - uses: actions/checkout@v3
      - uses: Xuanwo/sccache-action@c94e27bef21ab3fb4a5152c8a878c53262b4abb0
        with:
          version: "v0.4.0-pre.6"
      - name: Start sccache
        run: ${SCCACHE_PATH} --start-server
        env:
          SCCACHE_GHA_VERSION: opendal
      - name: Test
        shell: bash
        run: cargo test memcached --features compress,services-memcached -- --nocapture
        env:
          RUSTC_WRAPPER: ${{ env.SCCACHE_PATH }}
          RUST_BACKTRACE: full
          RUST_LOG: debug
          OPENDAL_MEMCACHED_TEST: on
          OPENDAL_MEMCACHED_ENDPOINT: tcp://127.0.0.1:11211
          OPENDAL_MEMCACHED_ROOT: /
