name: Service Test Obs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  obs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Xuanwo/sccache-action@c94e27bef21ab3fb4a5152c8a878c53262b4abb0
        with:
          version: "v0.4.0-pre.6"
      - name: Start sccache
        run: ${SCCACHE_PATH} --start-server
        env:
          SCCACHE_GHA_ENABLED: on
      - name: Test
        shell: bash
        run: cargo test obs --features compress -- --nocapture
        env:
          RUSTC_WRAPPER: ${{ env.SCCACHE_PATH }}
          RUST_BACKTRACE: full
          RUST_LOG: debug
          OPENDAL_OBS_TEST: ${{ secrets.OPENDAL_OBS_TEST }}
          OPENDAL_OBS_BUCKET: ${{ secrets.OPENDAL_OBS_BUCKET }}
          OPENDAL_OBS_ENDPOINT: ${{ secrets.OPENDAL_OBS_ENDPOINT }}
          OPENDAL_OBS_ACCESS_KEY_ID: ${{ secrets.OPENDAL_OBS_ACCESS_KEY_ID }}
          OPENDAL_OBS_SECRET_ACCESS_KEY: ${{ secrets.OPENDAL_OBS_SECRET_ACCESS_KEY }}
