name: Service Test Ftp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  vsftpd:
    runs-on: ubuntu-latest

    services:
      ftp:
        image: fauria/vsftpd
        ports:
          - 2121:21
          - 20000-22000:20000-22000
        env:
          FTP_USER: admin
          FTP_PASS: admin
          PASV_ADDRESS: 127.0.0.1
          PASV_MIN_PORT: 20000
          PASV_MAX_PORT: 22000
        volumes:
          - vsftpd-data:/home/vsftpd

    steps:
      - uses: actions/checkout@v3
      - name: Set swap
        shell: bash
        run: |
          SWAP_PATH="swapfile"

          sudo fallocate -l 10G $SWAP_PATH
          sudo chmod 600 $SWAP_PATH
          sudo mkswap $SWAP_PATH
          sudo swapon $SWAP_PATH
      - name: Swap space report after modification
        shell: bash
        run: |
          echo "Memory and swap:"
          free -h
          echo
          swapon --show
          echo

      - uses: Xuanwo/sccache-action@c94e27bef21ab3fb4a5152c8a878c53262b4abb0
        with:
          version: "v0.4.0-pre.5"
      - name: Start sccache
        run: ${SCCACHE_PATH} --start-server
        env:
          SCCACHE_GHA_VERSION: opendal
      - name: Test
        shell: bash
        run: cargo test ftp --features compress,services-ftp -- --nocapture
        env:
          RUSTC_WRAPPER: ${{ env.SCCACHE_PATH }}
          RUST_BACKTRACE: full
          RUST_LOG: debug
          OPENDAL_FTP_TEST: on
          OPENDAL_FTP_ENDPOINT: ftp://127.0.0.1:2121
          OPENDAL_FTP_ROOT: /
          OPENDAL_FTP_USER: admin
          OPENDAL_FTP_PASSWORD: admin
